# Generated by Django 3.2.9 on 2021-12-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nustomer_name', models.CharField(max_length=50)),
                ('name_barber', models.CharField(choices=[('1', 'Amin'), ('2', 'Mehrdad'), ('3', 'Na'), ('4', 'Nima')], max_length=1)),
                ('slug', models.SlugField()),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
