# Generated by Django 3.2.9 on 2021-12-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='nustomer_name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='turn',
            name='name_barber',
            field=models.CharField(choices=[('1', 'Amin'), ('2', 'Mehrdad'), ('3', 'Navid'), ('4', 'Nima')], max_length=1),
        ),
    ]
