# Generated by Django 3.2.9 on 2021-12-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('name_barber', models.CharField(choices=[('1', 'Amin'), ('2', 'Mehrdad'), ('3', 'Navid'), ('4', 'Nima')], max_length=1)),
                ('slug', models.SlugField()),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
