# Generated by Django 3.2.9 on 2021-12-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Turns', '0002_alter_turn_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='author',
        ),
        migrations.AddField(
            model_name='turn',
            name='registrar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
