# Generated by Django 3.2.9 on 2021-12-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0003_auto_20211220_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='registrar',
            new_name='user_registrar',
        ),
    ]
