# Generated by Django 3.2.9 on 2021-12-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0004_rename_registrar_turn_user_registrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='user_registrar',
            new_name='author',
        ),
    ]
