# Generated by Django 3.2.9 on 2021-12-21 14:22

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0005_rename_user_registrar_turn_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datetime', django_jalali.db.models.jDateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='turn',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
