# Generated by Django 3.2.9 on 2021-12-21 14:23

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0006_auto_20211221_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='date1',
            field=django_jalali.db.models.jDateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
