# Generated by Django 3.2.9 on 2021-12-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turns', '0007_auto_20211221_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarTime',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='date1',
        ),
    ]
